'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cheatlyzer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cmbValHP2=00
        '''cmbValHP1=00
        '''cmbValHP0=00
        '''cmbValMana2=00
        '''cmbKeyHP2=--
        '''cmbKeyMana2=--
        '''cmbKeyHP1=--
        '''cmbKeyMana0=--
        '''cmbKeyHP0=--
        '''cmbValMana1=00
        '''cmbKeyMana1=--
        '''cmbValMana0=00
        '''checkHealerEnabled=0
        '''numericRecastMana2=2000
        '''numericRecastMana1=2000
        '''numericRecastMana0=2000
        '''numericRecastHP2=2000
        '''numericRecastHP1=2000
        '''numericRecastHP0=2000
        '''checkAntiAFKEnabled=0
        '''numericAntiAFKMaximum=60
        '''numericAntiAFKMinimum=20
        '''cmbValManaTrainNearMax=95
        '''cmbKeyManaTrain=--
        '''checkManaTrainEnabled=0
        '''numericRecastManaTr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _default() As String
            Get
                Return ResourceManager.GetString("_default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Memory]
        '''; [[[[[[[[[[[[[[[[[[[[[[[[[[[
        '''; BEGIN AUTOMATIC UPDATE ZONE
        '''version=11.01
        '''tibiamainname=client
        '''tibiaclassname=Qt5QWindowOwnDCIcon
        '''tibiatitle=Tibia
        '''tibiamainname_updater=tibia
        '''tibiaclassname_updater=Qt5QWindowIcon
        '''tibiatitle_updater=Tibia
        '''adrChatLog_tabStruct=&quot;Qt5Core.dll&quot; + 4555C8 &gt; 8 &gt; 118
        '''adrServerList_CollectionStart=&quot;Qt5Core.dll&quot; + 4555C8 &gt; 8 &gt; 168 &gt; 54 &gt; 18 &gt; 2c
        '''adrSkills_CollectionStart=&quot;Qt5Core.dll&quot; + 004555C8 &gt; 8 &gt; 1D8 &gt; 60 &gt; 9c
        '''adrXPos=&quot;Qt5Core.dll&quot; + 004555C8 &gt; 8 &gt; 134 &gt; 24 &gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property config1101() As String
            Get
                Return ResourceManager.GetString("config1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Memory]
        '''; [[[[[[[[[[[[[[[[[[[[[[[[[[[
        '''; BEGIN - MEMORY PATHS
        '''version=11.02
        '''tibiamainname=client
        '''tibiaclassname=Qt5QWindowOwnDCIcon
        '''tibiatitle=Tibia
        '''tibiamainname_updater=tibia
        '''tibiaclassname_updater=Qt5QWindowIcon
        '''tibiatitle_updater=Tibia
        '''adrSelectedItem_height=&quot;Qt5Widgets.dll&quot; + 00401DC4 &gt; 70 &gt; 4 &gt; a8
        '''
        '''adrGameRect_Width_Double=&quot;Qt5Core.dll&quot; + 004555C8 &gt; 8 &gt; 10C &gt; 18 &gt; 4 &gt; 74 &gt; 4 &gt; 88
        '''
        '''adrChatLog_tabStruct=&quot;Qt5Core.dll&quot; + 4555C8 &gt; 8 &gt; 118
        '''SELECTEDCHANNEL_FirstLineText_Unicode=&quot;Qt5Core.dll &quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property config1102() As String
            Get
                Return ResourceManager.GetString("config1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Memory]
        '''; [[[[[[[[[[[[[[[[[[[[[[[[[[[
        '''; BEGIN - MEMORY PATHS
        '''version=11.03
        '''tibiamainname=client
        '''tibiaclassname=Qt5QWindowOwnDCIcon
        '''tibiatitle=Tibia
        '''tibiamainname_updater=tibia
        '''tibiaclassname_updater=Qt5QWindowIcon
        '''tibiatitle_updater=Tibia
        '''adrSelectedItem_height=&quot;Qt5Widgets.dll&quot; + 00401DC4 &gt; 70 &gt; 4 &gt; a8
        '''
        '''adrGameRect_Width_Double=&quot;Qt5Core.dll&quot; + 004555C8 &gt; 8 &gt; 10C &gt; 18 &gt; 4 &gt; 74 &gt; 4 &gt; 88
        '''
        '''adrChatLog_tabStruct=&quot;Qt5Core.dll&quot; + 4555C8 &gt; 8 &gt; 118
        '''SELECTEDCHANNEL_FirstLineText_Unicode=&quot;Qt5Core.dll &quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property config1103() As String
            Get
                Return ResourceManager.GetString("config1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Memory]
        '''; [[[[[[[[[[[[[[[[[[[[[[[[[[[
        '''; BEGIN - MEMORY PATHS
        '''version=11.04
        '''tibiamainname=client
        '''tibiaclassname=Qt5QWindowOwnDCIcon
        '''tibiatitle=Tibia
        '''tibiamainname_updater=tibia
        '''tibiaclassname_updater=Qt5QWindowIcon
        '''tibiatitle_updater=Tibia
        '''adrSelectedItem_height=&quot;Qt5Widgets.dll&quot; + 00401DC4 &gt; 70 &gt; 4 &gt; a8
        '''
        '''adrGameRect_Width_Double=&quot;Qt5Core.dll&quot; + 004555C8 &gt; 8 &gt; 10C &gt; 18 &gt; 4 &gt; 74 &gt; 4 &gt; 88
        '''
        '''adrChatLog_tabStruct=&quot;Qt5Core.dll&quot; + 4555C8 &gt; 8 &gt; 118
        '''SELECTEDCHANNEL_FirstLineText_Unicode=&quot;Qt5Core.dll &quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property config1104() As String
            Get
                Return ResourceManager.GetString("config1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Memory]
        '''; [[[[[[[[[[[[[[[[[[[[[[[[[[[
        '''; BEGIN - MEMORY PATHS
        '''version=11.04
        '''tibiamainname=client
        '''tibiaclassname=Qt5QWindowOwnDCIcon
        '''tibiatitle=Tibia
        '''tibiamainname_updater=tibia
        '''tibiaclassname_updater=Qt5QWindowIcon
        '''tibiatitle_updater=Tibia
        '''adrSelectedItem_height=&quot;Qt5Widgets.dll&quot; + 00401DC4 &gt; 70 &gt; 4 &gt; a8
        '''
        '''adrGameRect_Width_Double=&quot;Qt5Core.dll&quot; + 004555C8 &gt; 8 &gt; 10C &gt; 18 &gt; 4 &gt; 74 &gt; 4 &gt; 88
        '''
        '''adrChatLog_tabStruct=&quot;Qt5Core.dll&quot; + 4555C8 &gt; 8 &gt; 118
        '''SELECTEDCHANNEL_FirstLineText_Unicode=&quot;Qt5Core.dll &quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property config1110() As String
            Get
                Return ResourceManager.GetString("config1110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property miniIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miniIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Global]
        '''AddressFile=config1104.ini
        '''timerMS=100
        '''totalFriends=0
        '''settingsVersion=124.
        '''</summary>
        Friend ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tibia_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tibia_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
